### ISSUE TITLE
Updating broken

### ISSUE THREAD

**Issue by subworx** [Nazky/GoldCheats-Updater#1]
Hi,
lovely tool but updating is broken now, worked fine before.

Using the only available version.
Steps to reproduce:
- Launch program
- Click "Update all cheats"

Expected result: cheats are downloaded and displayed.

Actual result (replace <exe_location> with E:\ps4\tools or wherever the executable is):
- Receive error popup "Could not find a part of the path '<exe_location>\kmeps4\json'.
- Empty list in program
- Empty directory <exe_location>\json
- Directory filled with json files at <exe_location>\kmeps4.

Thanks and regards.

**Comment by Nazky** [comment]
fix with the last update
